services:
  postgres:
    image: postgres:15
    container_name: gowheels_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gowheels_db
      POSTGRES_USER: gowheels_user
      POSTGRES_PASSWORD: gowheels_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: gowheels_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: gowheels_admin
      MONGO_INITDB_ROOT_PASSWORD: gowheels_admin_pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:

