version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gowheels_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gowheels_db
      POSTGRES_USER: gowheels_user
      POSTGRES_PASSWORD: gowheels_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
